[package]
name = "messoria-client"
description = "Rendering, input and presentation for the Messoria game client."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license-file.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
bevy = { workspace = true, features = ["3d", "ui"] }
lightyear.workspace = true
messoria-calendar.workspace = true
messoria-content.workspace = true
messoria-farming.workspace = true
messoria-inventory.workspace = true
messoria-shared.workspace = true
messoria-voxel.workspace = true
rand.workspace = true

[lints]
workspace = true
